mod ai;
mod geo;
mod time;
mod verify;

use crate::time::now_iso;
use axum::{extract::{Path, State}, http::StatusCode, response::{IntoResponse, Json}, routing::{get, post}, Router};
use rand::{rngs::OsRng, RngCore};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, sync::{Arc, Mutex}, time::{Duration, SystemTime, UNIX_EPOCH}};
use tokio::process::Command;
use tower_http::{cors::{Any, CorsLayer}, trace::TraceLayer};

#[derive(Clone)] struct AppState { http_client:reqwest::Client, scripts_dir:String, vkey_path:String, verifications:Arc<Mutex<HashMap<String,StoredVerification>>>, evidence_sessions:Arc<Mutex<HashMap<String,EvidenceSession>>> }
#[derive(Deserialize)] #[serde(deny_unknown_fields)] struct CheckLocationRequest { latitude:f64, longitude:f64, cutoff_year:u16 }
#[derive(Debug,Clone,Serialize,Deserialize)] struct StoredVerification { verification_id:String, created_at:String, zk_proof_valid:bool, compliance_status:String, failed_checks:Vec<String>, proof:serde_json::Value, public_signals:serde_json::Value, #[serde(skip_serializing_if="Option::is_none")] evidence:Option<PublicEvidence> }
#[derive(Debug,Clone,Serialize,Deserialize)] struct PublicEvidence { evidence_hash:String, protected_area:PublicProtectedEvidence, land_cover:PublicLandCoverEvidence, forest_loss:PublicForestLossEvidence }
#[derive(Debug,Clone,Serialize,Deserialize)] struct PublicProtectedEvidence { status:bool, source:String, dataset:String, query_radius_m:u32, source_url:String, retrieved_at:String }
#[derive(Debug,Clone,Serialize,Deserialize)] struct PublicLandCoverEvidence { classification:String, code:i64, source:String, dataset:String, source_url:String, retrieved_at:String, note:String, raw_response_sha256:String }
#[derive(Debug,Clone,Serialize,Deserialize)] struct PublicForestLossEvidence { status:bool, source:String, dataset:String, source_url:String, cutoff_year:u16, first_loss_year_after_cutoff:Option<u16>, loss_area_ha_after_cutoff:f64, query_radius_m:u32, raw_response_sha256:String, retrieved_at:String, note:String }
#[derive(Debug,Clone)] struct EvidenceSession { evidence_hash:String, cutoff_year:u16, evidence:PublicEvidence, created_unix_secs:u64 }
#[derive(Debug,Deserialize)] struct VerifyProofRequest { proof:serde_json::Value, public_signals:serde_json::Value, evidence_session:String }

async fn check_location(State(state):State<Arc<AppState>>,Json(req):Json<CheckLocationRequest>)->impl IntoResponse{match geo::check_location(&state.http_client,req.latitude,req.longitude,req.cutoff_year).await{Ok(evidence)=>match create_evidence_session(&state,&evidence).await{Ok((id,hash))=>(StatusCode::OK,Json(serde_json::json!({"ok":true,"evidence":evidence,"evidence_session":id,"evidence_hash":hash,"evidence_commitment":{"algorithm":"Poseidon(5) over encoded coordinate + protected flag + land-cover code + post-cutoff loss year","evidence_hash":hash}}))),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"error":e})))},Err(e)=>(StatusCode::BAD_GATEWAY,Json(serde_json::json!({"ok":false,"error":e.to_string(),"note":"No fallback environmental data was substituted. Fix the failing source or configuration and retry."})))} }
async fn verify_proof_handler(State(state):State<Arc<AppState>>,Json(req):Json<VerifyProofRequest>)->impl IntoResponse{let session=match take_evidence_session(&state,&req.evidence_session){Ok(s)=>s,Err(e)=>return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"error":e}))) };if let Err(e)=validate_public_signals(&req.public_signals,&session.evidence_hash,session.cutoff_year){return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"error":e})));}let(compliance_status,failed_checks)=extract_compliance_status(&req.public_signals);match verify::verify_proof(&state.scripts_dir,&state.vkey_path,&verify::VerifyRequest{proof:req.proof.clone(),public_signals:req.public_signals.clone()}).await{Ok(result)=>{if !result.zk_proof_valid{return(StatusCode::OK,Json(serde_json::json!({"ok":true,"zk_proof_valid":false,"private_coordinates_disclosed":false,"private_quantity_disclosed":false,"supplier_secret_disclosed":false,"log":result.raw_stdout})));}let id=create_verification_id();let stored=StoredVerification{verification_id:id.clone(),created_at:now_iso(),zk_proof_valid:true,compliance_status:compliance_status.clone(),failed_checks:failed_checks.clone(),proof:req.proof,public_signals:req.public_signals,evidence:Some(session.evidence)};match state.verifications.lock(){Ok(mut db)=>{db.insert(id.clone(),stored.clone());},Err(_)=>return(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"error":"verification store unavailable"}))),}(StatusCode::OK,Json(serde_json::json!({"ok":true,"zk_proof_valid":true,"verification_id":id,"created_at":stored.created_at,"compliance_status":compliance_status,"failed_checks":failed_checks,"private_coordinates_disclosed":false,"private_quantity_disclosed":false,"supplier_secret_disclosed":false})))},Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"error":e.to_string()})))}}
const SESSION_TTL_SECS:u64=10*60;const EXPECTED_PUBLIC_SIGNALS:usize=16;const DEFAULT_LAT_MIN:u64=94_000_000;const DEFAULT_LAT_MAX:u64=101_500_000;const DEFAULT_LON_MIN:u64=171_400_000;const DEFAULT_LON_MAX:u64=181_500_000;const DEFAULT_QUANTITY_THRESHOLD:u64=5_000;const DEFAULT_ALLOWED_LAND_COVER:u64=40;
async fn create_evidence_session(state:&AppState,e:&geo::LocationEvidence)->Result<(String,String),String>{let lat_enc=((e.latitude+90.0)*1_000_000.0).round()as u64;let lon_enc=((e.longitude+180.0)*1_000_000.0).round()as u64;let protected=if e.protected_area.status{1}else{0};let loss_year=e.forest_loss.first_loss_year_after_cutoff.unwrap_or(0);let output=Command::new("node").arg(format!("{}/evidence-hash.js",state.scripts_dir)).arg(lat_enc.to_string()).arg(lon_enc.to_string()).arg(protected.to_string()).arg(e.land_cover.code.to_string()).arg(loss_year.to_string()).output().await.map_err(|x|format!("failed to calculate evidence commitment: {x}"))?;if !output.status.success(){return Err("failed to calculate evidence commitment".into())}let hash=String::from_utf8_lossy(&output.stdout).trim().to_string();if hash.is_empty(){return Err("empty evidence commitment".into())}let evidence=PublicEvidence{evidence_hash:hash.clone(),protected_area:PublicProtectedEvidence{status:e.protected_area.status,source:e.protected_area.source.into(),dataset:e.protected_area.dataset.into(),query_radius_m:e.protected_area.query_radius_m,source_url:e.protected_area.source_url.clone(),retrieved_at:e.protected_area.retrieved_at.clone()},land_cover:PublicLandCoverEvidence{classification:e.land_cover.classification.clone(),code:e.land_cover.code,source:e.land_cover.source.into(),dataset:e.land_cover.dataset.into(),source_url:e.land_cover.source_url.clone(),retrieved_at:e.land_cover.retrieved_at.clone(),note:e.land_cover.note.into(),raw_response_sha256:e.land_cover.raw_response_sha256.clone()},forest_loss:PublicForestLossEvidence{status:e.forest_loss.status,source:e.forest_loss.source.into(),dataset:e.forest_loss.dataset.into(),source_url:e.forest_loss.source_url.clone(),cutoff_year:e.forest_loss.cutoff_year,first_loss_year_after_cutoff:e.forest_loss.first_loss_year_after_cutoff,loss_area_ha_after_cutoff:e.forest_loss.loss_area_ha_after_cutoff,query_radius_m:e.forest_loss.query_radius_m,raw_response_sha256:e.forest_loss.raw_response_sha256.clone(),retrieved_at:e.forest_loss.retrieved_at.clone(),note:e.forest_loss.note.into()}};let id=random_id("ES");state.evidence_sessions.lock().map_err(|_|"evidence session store unavailable".to_string())?.insert(id.clone(),EvidenceSession{evidence_hash:hash.clone(),cutoff_year:e.forest_loss.cutoff_year,evidence,created_unix_secs:unix_secs()});Ok((id,hash))}
fn take_evidence_session(state:&AppState,id:&str)->Result<EvidenceSession,String>{let now=unix_secs();let mut s=state.evidence_sessions.lock().map_err(|_|"evidence session store unavailable".to_string())?;s.retain(|_,v|now.saturating_sub(v.created_unix_secs)<=SESSION_TTL_SECS);s.remove(id).ok_or_else(||"Evidence session not found, expired, or already used. Run the environmental lookup again.".into())}
fn extract_compliance_status(signals:&serde_json::Value)->(String,Vec<String>){let a=match signals.as_array(){Some(a)=>a,None=>return("UNKNOWN".into(),vec![])};let one=|i:usize|a.get(i).and_then(|v|v.as_str())==Some("1");let checks=[(1,"Region check"),(2,"Protected area check"),(3,"Land cover check"),(4,"Quantity threshold check"),(5,"Supplier commitment check"),(6,"Forest-loss cutoff check"),(7,"Evidence binding check")];let failed=checks.iter().filter(|(i,_)|!one(*i)).map(|(_,n)|n.to_string()).collect();(if one(0){"COMPLIANT".into()}else{"NOT_COMPLIANT".into()},failed)}
fn validate_public_signals(signals:&serde_json::Value,evidence_hash:&str,cutoff_year:u16)->Result<(),String>{let a=signals.as_array().ok_or("public_signals must be an array")?;if a.len()!=EXPECTED_PUBLIC_SIGNALS{return Err(format!("unexpected public-signal count: expected {EXPECTED_PUBLIC_SIGNALS}, got {}",a.len()))}for i in 0..8{let v=a[i].as_str().unwrap_or("");if v!="0"&&v!="1"{return Err(format!("output signal {i} is not a valid boolean"))}}let expected=[(8,DEFAULT_LAT_MIN.to_string()),(9,DEFAULT_LAT_MAX.to_string()),(10,DEFAULT_LON_MIN.to_string()),(11,DEFAULT_LON_MAX.to_string()),(12,DEFAULT_QUANTITY_THRESHOLD.to_string()),(13,cutoff_year.to_string()),(15,evidence_hash.to_string())];for(i,v)in expected{if a[i].as_str()!=Some(v.as_str()){return Err(format!("public signal {i} does not match the evidence session or deployed policy"))}}if a[14].as_str().map(|s|s.is_empty()).unwrap_or(true){return Err("supplier commitment public signal is missing".into())}Ok(())}
fn unix_secs()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}fn random_id(prefix:&str)->String{let mut b=[0u8;16];OsRng.fill_bytes(&mut b);format!("{prefix}-{}",b.iter().map(|x|format!("{x:02X}")).collect::<String>())}
async fn get_verification(State(state):State<Arc<AppState>>,Path(id):Path<String>)->impl IntoResponse{match state.verifications.lock(){Ok(db)=>match db.get(&id){Some(v)=>(StatusCode::OK,Json(serde_json::json!({"ok":true,"verification_id":v.verification_id,"created_at":v.created_at,"zk_proof_valid":v.zk_proof_valid,"compliance_status":v.compliance_status,"failed_checks":v.failed_checks,"evidence":v.evidence,"public_signals":v.public_signals}))),None=>(StatusCode::NOT_FOUND,Json(serde_json::json!({"ok":false,"error":"Verification ID not found or expired."})))},Err(_)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"error":"verification store unavailable"})))}}
async fn health(State(state):State<Arc<AppState>>)->impl IntoResponse{let count=state.verifications.lock().map(|d|d.len()).unwrap_or(0);Json(serde_json::json!({"ok":true,"service":"greenproof-backend","verification_count":count,"storage":"in-memory demo store","forest_loss_dataset":"Hansen/UMD GFC 2024 v1.12 via Global Forest Watch Data API"}))}
fn create_verification_id()->String{random_id("GP")}
#[cfg(test)]mod tests{use super::*;#[test]fn request_rejects_unknown_fields(){assert!(serde_json::from_str::<CheckLocationRequest>(r#"{"latitude":6.6,"longitude":-1.6,"foo":1,"cutoff_year":2020}"#).is_err());assert!(serde_json::from_str::<CheckLocationRequest>(r#"{"latitude":6.6,"longitude":-1.6,"cutoff_year":2020}"#).is_ok());}}
#[tokio::main]async fn main(){dotenvy::dotenv().ok();tracing_subscriber::fmt().with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_|"info,greenproof_backend=info".into())).init();let scripts_dir=std::env::var("GREENPROOF_SCRIPTS_DIR").unwrap_or_else(|_|"../scripts".into());let vkey_path=std::env::var("GREENPROOF_VKEY_PATH").unwrap_or_else(|_|"../circuits/build/verification_key.json".into());let state=Arc::new(AppState{http_client:reqwest::Client::builder().timeout(Duration::from_secs(20)).build().expect("failed to build reqwest client"),scripts_dir,vkey_path,verifications:Arc::new(Mutex::new(HashMap::new())),evidence_sessions:Arc::new(Mutex::new(HashMap::new()))});let cors=CorsLayer::new().allow_origin(Any).allow_methods(Any).allow_headers(Any);let app=Router::new().route("/api/health",get(health)).route("/api/check-location",post(check_location)).route("/api/verify-proof",post(verify_proof_handler)).route("/api/verifications/:id",get(get_verification)).route("/api/ai-audit",post(ai::ai_audit_handler)).layer(cors).layer(TraceLayer::new_for_http()).with_state(state);let addr=std::env::var("GREENPROOF_BACKEND_ADDR").unwrap_or_else(|_|"0.0.0.0:8080".into());let listener=tokio::net::TcpListener::bind(&addr).await.expect("bind failed");tracing::info!("GreenProof backend listening on {addr}");axum::serve(listener,app).await.expect("server error");}
