import { useEffect, useMemo, useState, type ReactNode } from "react";
import { MapContainer, TileLayer, Marker, Popup, useMap, useMapEvents } from "react-leaflet";
import { generateProof, verifyProofLocally, parseComplianceChecks, type RegionConfig } from "./lib/zk";
import "./app.css";

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:8080";
const DEFAULT_REGION: RegionConfig = { minLat: 4, maxLat: 11.5, minLon: -8.6, maxLon: 1.5 };
const DEFAULT_THRESHOLD_KG = 5000;
const DEFAULT_ALLOWED_LAND_COVER_CODE = 40;
const DEFAULT_CUTOFF_YEAR = 2020;
const WORKFLOW_STAGES = ["Private inputs", "Environmental evidence", "Generate proof", "Verify", "Result"];

type EvidenceState = { ok:boolean; evidence?:any; evidence_session?:string; evidence_hash?:string; error?:string; note?:string };

export default function App(){
  const [tab,setTab]=useState<"supplier"|"auditor">(()=>new URLSearchParams(location.search).get("verification")?"auditor":"supplier");
  const [verificationId,setVerificationId]=useState<string|null>(()=>new URLSearchParams(location.search).get("verification"));
  const createId=(id:string)=>{setVerificationId(id);history.replaceState({},"",`?verification=${encodeURIComponent(id)}`);setTab("auditor")};
  return <div className="app-shell"><div className="page">
    <header className="topbar"><div className="brand"><span className="brand-mark"/><div><strong>GreenProof</strong><span>Environmental compliance · Privacy</span></div></div><nav className="tabs"><button className={tab==="supplier"?"active":""} onClick={()=>setTab("supplier")}>Supplier</button><button className={tab==="auditor"?"active":""} onClick={()=>setTab("auditor")}>Auditor</button></nav></header>
    <section className="hero"><div className="hero-copy-block"><p className="eyebrow">Privacy-preserving environmental verification</p><h1>Prove environmental compliance.<br/>Keep your location private.</h1><p className="hero-lead">GreenProof combines live forest-loss evidence with a zero-knowledge proof so the verifier learns the policy result, not the exact farm coordinates.</p><div className="hero-actions"><button className="btn btn-primary" onClick={()=>setTab("supplier")}>Start verification</button><button className="btn btn-ghost" onClick={()=>setTab("auditor")}>View as auditor</button></div></div><div className="concept-flow"><ConceptStep index="01" title="Private site" detail="Exact coordinates stay protected"/><div className="concept-arrow"/><ConceptStep index="02" title="Forest-loss evidence" detail="Hansen/UMD Landsat data"/><div className="concept-arrow"/><ConceptStep index="03" title="Zero-knowledge proof" detail="Policy without disclosure"/><div className="concept-arrow"/><ConceptStep index="04" title="Verified result" detail="Cryptographically checkable" highlight/></div></section>
    <section className="privacy-split"><article className="split-card split-knows"><p className="split-label">Supplier knows</p><ul><li>Exact coordinates</li><li>Production quantity</li><li>Supplier secret</li></ul></article><article className="split-card split-receives"><p className="split-label">Auditor receives</p><ul><li>Policy result</li><li>Dataset provenance</li><li>Cryptographic proof</li></ul></article><article className="split-card split-hidden"><p className="split-label">Auditor does not receive</p><ul><li>Exact coordinates</li><li>Private quantity</li><li>Supplier secret</li></ul></article></section>
    <div id="workflow">{tab==="supplier"?<SupplierView onVerificationCreated={createId}/>:<AuditorView initialId={verificationId}/>}</div>
    <footer className="site-footer"><p><strong>Technical limitation.</strong> Hansen/UMD Global Forest Change is a real Landsat-derived forest-loss dataset. GreenProof proves that the backend-retrieved claim was bound to the private witness and satisfied the configured cutoff predicate. It does not prove dataset completeness, legal EUDR compliance, or physical-world truth beyond the provider's data.</p></footer>
  </div></div>
}
function ConceptStep({index,title,detail,highlight}:{index:string;title:string;detail:string;highlight?:boolean}){return <div className={`concept-step${highlight?" concept-step-highlight":""}`}><span className="concept-index">{index}</span><strong>{title}</strong><span>{detail}</span></div>}
function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:string}){return <span className={`status-badge tone-${tone}`}>{children}</span>}
function MetaRow({label,value,badge,mono}:{label:string;value:ReactNode;badge?:ReactNode;mono?:boolean}){return <div className="meta-row"><span className="meta-label">{label}</span><div className="meta-value">{badge}<span className={mono?"mono":undefined}>{value}</span></div></div>}

function SupplierView({onVerificationCreated}:{onVerificationCreated:(id:string)=>void}){
  const [latitude,setLatitude]=useState("6.6666"),[longitude,setLongitude]=useState("-1.6163"),[quantityKg,setQuantityKg]=useState("1200"),[supplierId,setSupplierId]=useState(""),[supplierSecret,setSupplierSecret]=useState(""),[cutoffYear,setCutoffYear]=useState(String(DEFAULT_CUTOFF_YEAR));
  const [loading,setLoading]=useState(false),[evidenceState,setEvidenceState]=useState<EvidenceState|null>(null),[proofResult,setProofResult]=useState<any>(null),[proving,setProving]=useState(false),[error,setError]=useState<string|null>(null),[sharing,setSharing]=useState(false);
  const lat=Number(latitude),lon=Number(longitude),cutoff=Number(cutoffYear),mapValid=Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;
  const regionOk=mapValid&&lat>=DEFAULT_REGION.minLat&&lat<=DEFAULT_REGION.maxLat&&lon>=DEFAULT_REGION.minLon&&lon<=DEFAULT_REGION.maxLon;
  const evidence=evidenceState?.evidence;
  const forestPass=!!(evidence?.forest_loss?.status);
  const policySatisfied=!!(regionOk&&evidenceState?.ok&&!evidence.protected_area?.status&&evidence.land_cover?.code===DEFAULT_ALLOWED_LAND_COVER_CODE&&forestPass&&Number(quantityKg)<=DEFAULT_THRESHOLD_KG);

  async function checkEnvironmentalData(){
    setLoading(true);setEvidenceState(null);setProofResult(null);setError(null);
    try{const r=await fetch(`${BACKEND_URL}/api/check-location`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({latitude:lat,longitude:lon,cutoff_year:cutoff})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Environmental lookup failed");setEvidenceState(d)}catch(e:any){setEvidenceState({ok:false,error:e?.message||String(e)})}finally{setLoading(false)}
  }
  async function generateZkProof(){
    if(!evidenceState?.ok||!evidence||!evidenceState.evidence_hash){setError("Run the environmental lookup first.");return}if(!supplierId||!supplierSecret){setError("Enter a supplier identifier and secret. They remain local proof inputs.");return}const q=Number(quantityKg);if(!Number.isFinite(q)||q<0){setError("Production quantity must be a non-negative number.");return}
    setProving(true);setError(null);setProofResult(null);try{const result=await generateProof({latitude:lat,longitude:lon,quantityKg:q,supplierId,supplierSecret,region:DEFAULT_REGION,quantityThresholdKg:DEFAULT_THRESHOLD_KG,allowedLandCoverCode:DEFAULT_ALLOWED_LAND_COVER_CODE,cutoffYear:cutoff,evidenceProtectedFlag:evidence.protected_area.status,evidenceLandCoverCode:evidence.land_cover.code,evidenceFirstLossYearAfterCutoff:evidence.forest_loss.first_loss_year_after_cutoff??0,evidenceHash:evidenceState.evidence_hash});setProofResult(result)}catch(e:any){setError(e?.message||String(e))}finally{setProving(false)}
  }
  async function verifyAndShare(){if(!proofResult||!evidenceState?.evidence_session)return;setSharing(true);setError(null);try{const r=await fetch(`${BACKEND_URL}/api/verify-proof`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({proof:proofResult.proof,public_signals:proofResult.publicSignals,evidence_session:evidenceState.evidence_session})});const d=await r.json();if(!r.ok||!d.zk_proof_valid)throw new Error(d.error||"Proof verification failed");onVerificationCreated(d.verification_id)}catch(e:any){setError(e?.message||String(e))}finally{setSharing(false)}}
  const stages=WORKFLOW_STAGES.map((x,i)=>({id:i+1,label:x,status:i===0?"completed":i===1?(loading?"processing":evidenceState?evidenceState.ok?"completed":"failed":"active"):i===2?(proving?"processing":proofResult?"completed":evidenceState?.ok?"active":"idle"):i===3?(sharing?"processing":proofResult?"active":"idle"):"idle"}));
  return <main className="main-panel"><div className="panel-header"><div><p className="eyebrow">Supplier workflow</p><h2>Create a private forest-loss compliance proof</h2><p className="panel-desc">Coordinates are used for live environmental lookup. Quantity, supplier identity and secret remain local.</p></div><div className="constraint-card"><p className="split-label">Public policy</p><MetaRow label="Region" value="West African cocoa belt"/><MetaRow label="Quantity" value={`≤ ${DEFAULT_THRESHOLD_KG.toLocaleString()} kg`}/><MetaRow label="Land cover" value="Code 40 · cropland"/><MetaRow label="Forest loss" value={`None after ${cutoffYear}`}/></div></div>
    <ol className="workflow-progress">{stages.map(s=><li key={s.id} className={`progress-step progress-${s.status}`}><div className="progress-node"><span className="progress-num">{String(s.id).padStart(2,"0")}</span></div><span className="progress-label">{s.label}</span></li>)}</ol>
    <div className="workflow-grid"><section className="card stage-card"><div className="card-header"><div><p className="card-kicker">01 · Private inputs</p><h3>Sensitive site data</h3></div><StatusBadge tone="private">Private</StatusBadge></div>
      <div className="private-fields"><div className="field-group"><label htmlFor="lat">Exact coordinates</label><div className="two-col"><input id="lat" value={latitude} onChange={e=>setLatitude(e.target.value)} inputMode="decimal"/><input value={longitude} onChange={e=>setLongitude(e.target.value)} inputMode="decimal" aria-label="Longitude"/></div><small className={regionOk?"":"fail"}>{mapValid?(regionOk?"Inside supported cocoa region":"Outside supported cocoa region"):"Enter valid coordinates"}</small></div>
      <div className="field-group"><label htmlFor="cutoff">Forest-loss cutoff year</label><input id="cutoff" type="number" min="2001" max="2024" value={cutoffYear} onChange={e=>setCutoffYear(e.target.value)}/><small>Policy: no detected Hansen/UMD forest loss after this year.</small></div>
      <div className="field-group"><label htmlFor="qty">Production quantity (kg)</label><input id="qty" value={quantityKg} onChange={e=>setQuantityKg(e.target.value)} inputMode="decimal"/></div>
      <div className="field-group"><label htmlFor="sid">Supplier identifier</label><input id="sid" value={supplierId} onChange={e=>setSupplierId(e.target.value)} placeholder="Private identifier"/></div>
      <div className="field-group"><label htmlFor="secret">Supplier secret</label><input id="secret" type="password" value={supplierSecret} onChange={e=>setSupplierSecret(e.target.value)} placeholder="Local secret" autoComplete="off"/></div></div>
      <div className="privacy-strip"><StatusBadge tone="private">Private witness</StatusBadge><span>Coordinates, quantity, supplier ID and secret are not included in the final proof.</span></div>
      <button className="btn btn-primary wide" disabled={!mapValid||loading} onClick={checkEnvironmentalData}>{loading?"Checking live environmental data…":"Check environmental evidence"}</button>
    </section><section className="card map-card"><div className="card-header"><div><p className="card-kicker">Supplier-only view</p><h3>Exact plot location</h3></div><StatusBadge tone="private">Not shared</StatusBadge></div>{mapValid?<MapContainer center={[lat,lon]} zoom={9} style={{height:360,width:"100%"}}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapController lat={lat} lon={lon} onLocationSelect={(a,b)=>{setLatitude(a.toFixed(6));setLongitude(b.toFixed(6))}}/></MapContainer>:<div className="map-placeholder">Enter valid coordinates.</div>}<p className="map-note">The auditor does not receive this map or the exact coordinate.</p></section></div>
    {evidenceState&&!evidenceState.ok&&<section className="card failure-card"><div className="failure-icon">×</div><div><p className="card-kicker">02 · Environmental evidence</p><h3>Environmental evidence unavailable</h3><p>{evidenceState.error}</p><p className="muted">No fallback data was used.</p></div></section>}
    {evidenceState?.ok&&evidence&&<section className="card stage-card evidence-artifact"><div className="card-header"><div><p className="card-kicker">02 · Environmental evidence</p><h3>Live environmental evidence</h3></div><StatusBadge tone={policySatisfied?"success":"warn"}>{policySatisfied?"Policy satisfied":"Policy not satisfied"}</StatusBadge></div>
      <div className="artifact-grid"><MetaRow label="Forest dataset" value={evidence.forest_loss.dataset}/><MetaRow label="Cutoff" value={String(evidence.forest_loss.cutoff_year)}/><MetaRow label="Detected loss after cutoff" value={evidence.forest_loss.first_loss_year_after_cutoff??"None"}/><MetaRow label="Loss area in query" value={`${Number(evidence.forest_loss.loss_area_ha_after_cutoff).toFixed(6)} ha`}/><MetaRow label="Land cover" value={`${evidence.land_cover.classification} · code ${evidence.land_cover.code}`}/><MetaRow label="Protected area" value={evidence.protected_area.status?"Detected":"Not detected"}/></div>
      <div className="check-grid"><Check label="Supported region" pass={regionOk}/><Check label="Protected-area check" pass={!evidence.protected_area.status}/><Check label="Allowed land cover" pass={evidence.land_cover.code===DEFAULT_ALLOWED_LAND_COVER_CODE}/><Check label={`No forest loss after ${cutoffYear}`} pass={forestPass}/></div>
      <EvidencePanel evidence={evidence} evidenceHash={evidenceState.evidence_hash}/><button className="btn btn-primary wide" disabled={proving} onClick={generateZkProof}>{proving?"Generating zero-knowledge proof…":"Generate zero-knowledge proof"}</button>
    </section>}
    {proofResult&&<section className="card stage-card proof-card"><div className="card-header"><div><p className="card-kicker">03 · Zero-knowledge proof</p><h3>Proof generated</h3></div><StatusBadge tone={proofResult.compliant?"success":"warn"}>{proofResult.compliant?"Compliant":"Not compliant"}</StatusBadge></div><div className="check-grid"><Check label="Groth16 proof generated" pass/><Check label="Region check" pass={proofResult.checks.regionOk}/><Check label="Protected area check" pass={proofResult.checks.protectedAreaOk}/><Check label="Land cover check" pass={proofResult.checks.landCoverOk}/><Check label="Quantity threshold" pass={proofResult.checks.quantityOk}/><Check label="Forest-loss cutoff" pass={proofResult.checks.forestLossOk}/><Check label="Evidence binding" pass={proofResult.checks.evidenceOk}/></div>{!proofResult.compliant&&<div className="inline-warn"><strong>Policy not satisfied.</strong><span>{proofResult.preflightFailures.join("; ")}</span></div>}<button className="btn btn-primary" disabled={sharing} onClick={verifyAndShare}>{sharing?"Verifying proof…":"Verify & create share link"}</button></section>}
    {error&&<section className="card failure-card"><div className="failure-icon">×</div><div><h3>Verification step failed</h3><p>{error}</p></div></section>}
  </main>
}
function Check({label,pass}:{label:string;pass:boolean}){return <div className={`check ${pass?"check-pass":"check-private"}`}><span>{pass?"✓":"×"}</span><div><strong>{label}</strong><small>{pass?"Pass":"Fail"}</small></div></div>}
function EvidencePanel({evidence,evidenceHash}:{evidence:any;evidenceHash?:string}){return <div className="evidence-panel"><div className="evidence-head"><div><strong>Dataset provenance</strong><span>Live lookup · {evidence.forest_loss.retrieved_at}</span></div><StatusBadge tone="info">Source-backed</StatusBadge></div><div className="provenance-grid"><div><span>Forest loss</span><strong>{evidence.forest_loss.source}</strong><small>{evidence.forest_loss.dataset}</small></div><div><span>Land cover</span><strong>{evidence.land_cover.source}</strong><small>{evidence.land_cover.dataset}</small></div><div><span>Forest query</span><strong>{evidence.forest_loss.query_radius_m} m</strong><small>Approximate point-area query</small></div><div><span>Evidence hash</span><strong className="mono">{evidenceHash?.slice(0,24)}…</strong><small>Poseidon(5)</small></div></div><p className="source-note">{evidence.forest_loss.note}</p></div>}
function MapController({lat,lon,onLocationSelect}:{lat:number;lon:number;onLocationSelect:(lat:number,lon:number)=>void}){const map=useMap();useMapEvents({click:e=>onLocationSelect(e.latlng.lat,e.latlng.lng)});useEffect(()=>{map.setView([lat,lon],map.getZoom())},[lat,lon,map]);return <Marker position={[lat,lon]}><Popup>Private supplier coordinate.</Popup></Marker>}

function AuditorView({initialId}:{initialId:string|null}){
  const [id,setId]=useState(initialId||""),[result,setResult]=useState<any>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false),[proofText,setProofText]=useState(""),[signalsText,setSignalsText]=useState("");
  useEffect(()=>{if(initialId)load(initialId)},[initialId]);
  async function load(value:string){if(!value.trim())return;setLoading(true);setError(null);try{const r=await fetch(`${BACKEND_URL}/api/verifications/${encodeURIComponent(value.trim())}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Verification not found");setResult(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  async function verifyPasted(){try{const proof=JSON.parse(proofText),signals=JSON.parse(signalsText);setLoading(true);setResult({zk_proof_valid:await verifyProofLocally(proof,signals),public_signals:signals})}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  const checks=result?.public_signals?parseComplianceChecks(result.public_signals):null;const valid=result?.zk_proof_valid===true;
  return <main className="main-panel"><div className="panel-header"><div><p className="eyebrow">Auditor workflow</p><h2>Verify without seeing the farm</h2><p className="panel-desc">The auditor receives the cryptographic result and environmental provenance, not the exact coordinate or private witness.</p></div></div><section className={`card verification-card${valid?" is-valid":""}`}><div className="card-header"><div><p className="card-kicker">05 · Result</p><h3>GreenProof verification</h3></div>{result&&<StatusBadge tone={valid?"success":"danger"}>{valid?"Groth16 valid":"Invalid proof"}</StatusBadge>}</div><div className="id-row"><input value={id} onChange={e=>setId(e.target.value)} placeholder="GP-…"/><button className="btn btn-primary" disabled={loading||!id} onClick={()=>load(id)}>{loading?"Checking…":"Verify ID"}</button></div>{error&&<div className="inline-fail"><strong>Verification failed</strong><span>{error}</span></div>}{result&&<div className="verification-result"><div className="proof-summary"><MetaRow label="Cryptographic proof" value={valid?"Valid":"Invalid"} badge={<StatusBadge tone={valid?"success":"danger"}>{valid?"VALID":"INVALID"}</StatusBadge>}/>{result.compliance_status&&<MetaRow label="Environmental policy" value={result.compliance_status}/>}<MetaRow label="Exact coordinates" value="Not disclosed" badge={<StatusBadge tone="private">Hidden</StatusBadge>}/><MetaRow label="Private quantity" value="Not disclosed" badge={<StatusBadge tone="private">Hidden</StatusBadge>}/></div>{checks&&<div className="check-grid"><Check label="Region" pass={checks.regionOk}/><Check label="Protected area" pass={checks.protectedAreaOk}/><Check label="Land cover" pass={checks.landCoverOk}/><Check label="Quantity" pass={checks.quantityOk}/><Check label="Forest-loss cutoff" pass={checks.forestLossOk}/><Check label="Evidence binding" pass={checks.evidenceOk}/></div>}{result.evidence?.forest_loss&&<div className="evidence-panel"><div className="provenance-grid"><div><span>Forest-loss dataset</span><strong>{result.evidence.forest_loss.source}</strong><small>{result.evidence.forest_loss.dataset}</small></div><div><span>Cutoff</span><strong>{result.evidence.forest_loss.cutoff_year}</strong><small>Configured policy</small></div><div><span>Detected loss</span><strong>{result.evidence.forest_loss.first_loss_year_after_cutoff??"None"}</strong><small>After cutoff</small></div><div><span>Coordinates</span><strong>Hidden</strong><small>Protected by ZK</small></div></div></div>}</div>}</section><details className="card tech-details"><summary>Verify pasted proof artifacts</summary><div className="tech-body"><textarea value={proofText} onChange={e=>setProofText(e.target.value)} placeholder="proof.json"/><textarea value={signalsText} onChange={e=>setSignalsText(e.target.value)} placeholder="public.json"/><button className="btn btn-primary" onClick={verifyPasted}>Verify locally</button></div></details></main>
}
