// Real Groth16 circuit tests. Run after `bash scripts/setup.sh`.
const assert=require("assert");const fs=require("fs");const path=require("path");const snarkjs=require("snarkjs");const{poseidon2,poseidon5}=require("poseidon-lite");const{encodeLat,encodeLon,boundingBoxEnc}=require("../lib/encode");
const BUILD_DIR=path.join(__dirname,"..","..","circuits","build");const WASM=path.join(BUILD_DIR,"environmental_compliance_js","environmental_compliance.wasm");const ZKEY=path.join(BUILD_DIR,"environmental_compliance_final.zkey");const VKEY=JSON.parse(fs.readFileSync(path.join(BUILD_DIR,"verification_key.json"),"utf8"));
const REGION={minLat:4,maxLat:11.5,minLon:-8.6,maxLon:1.5};const THRESHOLD=5000;const ALLOWED=40;
function strToField(s){let x=0n;for(const ch of Buffer.from(String(s),"utf8"))x=(x*256n+BigInt(ch))%(2n**200n);return x;}
function buildInput(o={}){const lat=o.lat??6.6666,lon=o.lon??-1.6163,qty=o.qty??1200,protectedFlag=o.protectedFlag??0,landCoverCode=o.landCoverCode??ALLOWED,cutoffYear=o.cutoffYear??2020,firstLossYearAfterCutoff=o.firstLossYearAfterCutoff??0;const a=encodeLat(lat),b=encodeLon(lon),bb=boundingBoxEnc(REGION.minLat,REGION.maxLat,REGION.minLon,REGION.maxLon);const id=strToField(o.supplierId??"supplier-42"),sec=strToField(o.supplierSecret??"correct-horse-battery-staple");const commitment=o.commitmentOverride??poseidon2([id,sec]);const evidence=o.evidenceHashOverride??poseidon5([a,b,BigInt(protectedFlag),BigInt(landCoverCode),BigInt(firstLossYearAfterCutoff)]);return{latEnc:a.toString(),lonEnc:b.toString(),quantity:String(qty),supplierId:id.toString(),supplierSecret:sec.toString(),protectedFlag:String(protectedFlag),landCoverCode:String(landCoverCode),firstLossYearAfterCutoff:String(firstLossYearAfterCutoff),latMin:String(bb.latMin),latMax:String(bb.latMax),lonMin:String(bb.lonMin),lonMax:String(bb.lonMax),quantityThreshold:String(THRESHOLD),allowedLandCoverCode:String(ALLOWED),cutoffYear:String(cutoffYear),supplierCommitment:String(commitment),evidenceHash:String(evidence)};}
async function prove(input){return snarkjs.groth16.fullProve(input,WASM,ZKEY)}
describe("GreenProof forest-loss environmental circuit",function(){this.timeout(120000);
it("valid no-loss witness generates and verifies",async()=>{const input=buildInput();const{proof,publicSignals}=await prove(input);assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.deepStrictEqual(publicSignals.slice(0,8),["1","1","1","1","1","1","1","1"]);});
it("loss after cutoff is exposed as forestLossOk=0 and valid=0",async()=>{const{proof,publicSignals}=await prove(buildInput({firstLossYearAfterCutoff:2023}));assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.strictEqual(publicSignals[6],"0");assert.strictEqual(publicSignals[0],"0");});
it("loss before/equal cutoff passes the cutoff predicate",async()=>{const{proof,publicSignals}=await prove(buildInput({cutoffYear:2020,firstLossYearAfterCutoff:0}));assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.strictEqual(publicSignals[6],"1");});
it("protected flag makes policy invalid",async()=>{const{proof,publicSignals}=await prove(buildInput({protectedFlag:1}));assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.strictEqual(publicSignals[2],"0");assert.strictEqual(publicSignals[0],"0");});
it("quantity above threshold makes policy invalid",async()=>{const{proof,publicSignals}=await prove(buildInput({qty:THRESHOLD+1}));assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.strictEqual(publicSignals[4],"0");assert.strictEqual(publicSignals[0],"0");});
it("tampered evidence commitment cannot satisfy evidence binding",async()=>{const{proof,publicSignals}=await prove(buildInput({evidenceHashOverride:123456789n}));assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,proof),true);assert.strictEqual(publicSignals[7],"0");assert.strictEqual(publicSignals[0],"0");});
it("tampered proof fails verification",async()=>{const{proof,publicSignals}=await prove(buildInput());const tampered=JSON.parse(JSON.stringify(proof));tampered.pi_a[0]=(BigInt(tampered.pi_a[0])+1n).toString();assert.strictEqual(await snarkjs.groth16.verify(VKEY,publicSignals,tampered),false);});
it("tampered public signals fail verification",async()=>{const{proof,publicSignals}=await prove(buildInput());const tampered=[...publicSignals];tampered[0]=(BigInt(tampered[0])+1n).toString();assert.strictEqual(await snarkjs.groth16.verify(VKEY,tampered,proof),false);});
it("auditor artifacts contain no private witness",async()=>{const input=buildInput();const{proof,publicSignals}=await prove(input);const serialized=JSON.stringify({proof,publicSignals});assert.ok(!serialized.includes(input.latEnc));assert.ok(!serialized.includes(input.lonEnc));assert.ok(!serialized.includes(input.supplierId));assert.ok(!serialized.includes(input.supplierSecret));});
it("coordinate validation rejects invalid values",()=>{assert.throws(()=>encodeLat(120));assert.throws(()=>encodeLon(220));});
});
